# Generated by Django 3.0.4 on 2020-03-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_holiday_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
